# Generated by Django 3.2.7 on 2022-01-01 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=uploads.models.get_upload_path)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(blank=True, max_length=32, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
